version: '3'

services:
  blog-server:
    build: ./docker/php
    image: blog-symfony
    depends_on:
      - db
      - db-test
    volumes:
      - ./:/application:cached
      - ./var/sessions:/application/var/sessions/

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog
    volumes:
      - ./tmp/db:/var/lib/mysql

  db-test:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog-test
    volumes:
      - ./tmp/test:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - blog-server

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
      - '1025:25'

